project_id = "zntotcpagkunvkwpubqu"

[functions.import-crm-clients]
verify_jwt = false

[functions.import-billing-data]
verify_jwt = false

[functions.firecrawl-enrich-company]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.generate-project-tasks]
verify_jwt = false